/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.ll.mitie;

public class SDPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        globalJNI.delete_SDPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SDPair() {
    this(globalJNI.new_SDPair__SWIG_0(), true);
  }

  public SDPair(String first, double second) {
    this(globalJNI.new_SDPair__SWIG_1(first, second), true);
  }

  public SDPair(SDPair p) {
    this(globalJNI.new_SDPair__SWIG_2(SDPair.getCPtr(p), p), true);
  }

  public void setFirst(String value) {
    globalJNI.SDPair_first_set(swigCPtr, this, value);
  }

  public String getFirst() {
    return globalJNI.SDPair_first_get(swigCPtr, this);
  }

  public void setSecond(double value) {
    globalJNI.SDPair_second_set(swigCPtr, this, value);
  }

  public double getSecond() {
    return globalJNI.SDPair_second_get(swigCPtr, this);
  }

}
